package enums;

public enum AuditOption {
    ATTENDANCE_CONSTRUCTOR("Constructor"),
    ATTENDANCE_GET_STUDENT("Get_student"),
    ATTENDANCE_GET_COURSE("Get_course"),
    ATTENDANCE_TOSTRING("To_string"),
    ATTENDANCE_COMPARETO("Compare_to"),
    COURSE_CONSTRUCTOR("Constructor"),
    COURSE_GET_YEAR("Get_year"),
    COURSE_GET_COLLEGE_YEAR("Get_college_year"),
    COURSE_GET_SEMESTER("Get_semester"),
    COURSE_GET_SUBJECT("Get_subject"),
    COURSE_GET_CODE("Get_code"),
    COURSE_SET_PROFESSOR("Set_professor"),
    COURSE_TOSTRING("To_string"),
    COURSE_COMPARETO("Compare_to"),
    GRADE_CONSTRUCTOR("Constructor"),
    GRADE_GET_STUDENT("Get_student"),
    GRADE_GET_COURSE("Get_course"),
    GRADE_GET_SCORE("Get_score"),
    GRADE_TOSTRING("To_string"),
    GRADE_COMPARETO("Compare_to"),
    PERSON_GET_FIRSTNAME("Get_first_name"),
    PERSON_GET_SURNAME("Get_surname"),
    PERSON_GET_DATEOFBIRTH("Get_date_of_birth"),
    PERSON_GET_CNP("Get_CNP"),
    PERSON_GET_FULL_NAME("Get_full name"),
    PROFESSOR_CONSTRUCTOR("Constructor"),
    PROFESSOR_ADD_COURSE("Add_course"),
    PROFESSOR_TOSTRING("To_string"),
    SPECIALIZATION_CONSTRUCTOR("Constructor"),
    SPECIALIZATION_GET_CODE("Get_code"),
    SPECIALIZATION_GET_DEGREE("Get_degree"),
    SPECIALIZATION_TOSTRING("To_string"),
    STUDENT_CONSTRUCTOR("Constructor"),
    STUDENT_GET_GROUP("Get_group"),
    STUDENT_ADD_GRADE("Add_grade"),
    STUDENT_TOSTRING("To_string"),
    STUDENT_COMPARETO("Compare_to"),
    STUDENT_CALCULATEAVERAGE_YEAR("Calculate_yearly_average grade"),
    STUDENT_CALCULATEAVERAGE_GLOBAL("Calculate_overall_average grade"),
    STUDENT_ADDSPECIALIZATION("Add_specialization"),
    STUDENTGROUP_CONSTRUCTOR("Constructor"),
    STUDENTGROUP_GET_SERIES("Get_series"),
    STUDENTGROUP_ADD_STUDENT("Add_student"),
    STUDENTGROUP_COMPARETO("Compare_to"),
    STUDENTGROUP_TOSTRING("To_string"),
    STUDENTSERIES_CONSTRUCTOR("Constructor"),
    STUDENTSERIES_COMPARETO("Compare_to"),
    STUDENTSERIES_ADD_GROUP("Add_group"),
    STUDENTSERIES_TOSTRING("To_string"),
    STUDENTUNIT_GET_ID("Get_ID"),
    STUDENTUNIT_GET_NUMBER("Get_number"),
    STUDENTUNIT_GET_YEAR("Get_year"),
    STUDENTUNIT_GET_SPECIALIZATION("Get_specialization"),
    STUDENTUNIT_GET_STUDENTS("Get_students"),
    STUDENTUNIT_GET_REPRESENTATIVE("Get_representative"),
    STUDENTUNIT_SET_REPRESENTATIVE("Set_representative"),
    STUDENTUNIT_ADD_STUDENT("Add_student"),
    SUBJECT_CONSTRUCTOR("Constructor"),
    SUBJECT_GET_CODE("Get_code"),
    SUBJECT_GET_NAME("Get_name"),
    SUBJECT_GET_CREDITS("Get_credits"),
    SUBJECT_GET_PARTICIPATESINTOTALGRADE("Get_participation_in_total_grade"),
    SUBJECT_GET_SPECIALIZATION("Get_specialization"),
    SUBJECT_TOSTRING("To_string"),
    SUBJECT_COMPARETO("Compare_to"),
    CSV_READER_READOBJECTS("Read_objects"),
    CSV_WRITER_INITIALIZE("Initialize_writer"),
    AUX_GET_SPECIALIZATIONS("Get_specializations"),
    AUX_GET_SERIES("Get_series"),
    AUX_GET_GROUPS("Get_groups"),
    AUX_GET_STUDENTS("Get_students"),
    AUX_GET_PROFESSORS("Get_professors"),
    AUX_GET_SUBJECTS("Get_subjects"),
    AUX_GET_COURSES("Get_courses"),
    AUX_GET_GRADES("Get_grades"),
    AUX_ADD_SPECIALIZATION("Add_specialization"),
    AUX_ADD_SERIES("Add_series"),
    AUX_ADD_GROUP("Add_group"),
    AUX_ADD_STUDENT("Add_student"),
    AUX_ADD_PROFESSOR("Add_professor"),
    AUX_ADD_SUBJECT("Add_subject"),
    AUX_ADD_COURSE("Add_course"),
    AUX_ADD_GRADE("Add_grade"),
    AUX_ADD_GROUP_TO_SERIES("Add_group_to_series"),
    AUX_SEARCH_STUDENT("Search_for_student"),
    AUX_LIST_STUDENT("List_information_of student"),
    AUX_SET_REPRESENTATIVE("Set_representative"),
    AUX_SEARCH_PROFESSOR("Search_for_professor"),
    AUX_SEARCH_SUBJECT("Search_for_subject"),
    AUX_SEARCH_SPECIALIZATION("Search_for_specialization"),
    AUX_SEARCH_COURSE("Search_for_course"),
    AUX_SEARCH_YEAR("Search_for_year"),
    AUX_SEARCH_SERIES("Search_for_series"),
    AUX_LIST_STUDENTS_IN_UNIT("List_students_in_group_or_series"),
    SERVICE_LOAD_DATA("Load_data"),
    SERVICE_ADD_STUDENT("Add_student"),
    SERVICE_LIST_STUDENT("List_information_of_student"),
    SERVICE_SET_REPRESENTATIVE("Set_group/series representative"),
    SERVICE_LIST_STUDENTS_IN_UNIT("List_students_in_group/series"),
    SERVICE_ADD_COURSE_TO_PROFESSOR("Add_course_to_professor"),
    SERVICE_ADD_GRADE_TO_STUDENT("Add_grade_to_student"),
    SERVICE_SHOW_YEARLY_AVERAGE("Show_yearly_average_grade_of_student"),
    SERVICE_SHOW_AVERAGE_IN_SERIES("Show_average_grade_of_series"),
    SERVICE_LIST_COURSES_OF_SUBJECT("List_courses_teaching_subject"),
    SERVICE_ADD_SPECIALIZATION_TO_STUDENT("Add_specialization_to_student"),
    ;

    private final String action;
    AuditOption(String action) {
        this.action = action;
    }

    public String getAction() {
        return action;
    }
}
